name: ONT_analysis
channels:
 - conda-forge
 - bioconda
 - defaults
 - epi2melabs
dependencies:
 - snakemake==7.18.2
 - python>=3.7.6
 - synapseclient
 - pychopper==2.7.2
 - minimap2==2.26
 - samtools==1.17
 - stringtie==2.2.1
 - gffcompare==0.12.6